package logic
{
	import mx.resources.IResourceManager;
	import mx.resources.ResourceBundle;
	
	public class ResourceLanguage
	{
		public function ResourceLanguage()
		{
		}
		
		public static function setChartResources(resourceManager:IResourceManager):void{
			var _resources:ResourceBundle=new ResourceBundle("en_US","ChartResources");
			_resources.content['DAY']="Day";
			_resources.content['MONTH']="Month";
			_resources.content['YEAR']="Year";
			_resources.content['TOTAL']="Total";
			_resources.content['7DAYS']="7 Days";
			_resources.content['7DAYSIN']="7 Days";
			_resources.content['12MONTHS']="12 Months";
			_resources.content['PLANTADMIN']="Plant admin:";
			_resources.content['PRINTER']="Printer:";
			_resources.content['PRINTTIME']="Print time:";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Total yield:";
			_resources.content['CO2']="CO2 avoided:";
			_resources.content['INVERTER']="Inverter:";
			_resources.content['MONITOR']="Monitor:";
			_resources.content['EVENT']="New error:";
			_resources.content['LASTIMPORT']="Last update:";
			_resources.content['REPORT']="Report";
			_resources.content['PRINTDATAERROR']="Print Data Error";
			_resources.content['PRINTERROR']="Print error";
			_resources.content['CHECKPRINTER']="Please check your printer";
			_resources.content['RESTOREBG']="Restore default background";
			_resources.content['UPLOADBG']="Upload the background picture";
			_resources.content['FULLSCREEN']="Fullscreen";
			_resources.content['PROMPT']="Prompt";
			_resources.content['PHOTOSIZE']="Photo size please no more than 5 M!";
			_resources.content['PHOTOFORMATERROR']="Picture format is not right!";
			_resources.content['PHOTOFORMAT']="From local to upload your picture of the power station, only supports JPG GIF PNG formats, and files less than 5M.";
			_resources.content['PREVIEW']="Preview icon";
			_resources.content['PIXELS']="80*80 pixels";
			_resources.content['PHOTOSELECT']="Select Photo";
			_resources.content['OK']="OK";
			_resources.content['CANCEL']="Cancel";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["January","February","March","April","May","June","July","August","September","October", "November", "December"];
			resourceManager.addResourceBundle(_resources);
			
			_resources=new ResourceBundle("zh_CN","ChartResources");
			_resources.content['DAY']="日";
			_resources.content['MONTH']="月";
			_resources.content['YEAR']="年";
			_resources.content['TOTAL']="总计";
			_resources.content['7DAYS']="7日";
			_resources.content['7DAYSIN']="7日内";
			_resources.content['12MONTHS']="12月内";
			_resources.content['PLANTADMIN']="电站管理员：";
			_resources.content['PRINTER']="打印员：";
			_resources.content['PRINTTIME']="打印时间：";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="总收益:";
			_resources.content['CO2']="CO2减排量:";
			_resources.content['INVERTER']="逆变器:";
			_resources.content['MONITOR']="监控器:";
			_resources.content['EVENT']="事件:";
			_resources.content['LASTIMPORT']="数据更新时间:";
			_resources.content['REPORT']="报告";
			_resources.content['PRINTDATAERROR']="打印数据错误";
			_resources.content['PRINTERROR']="打印错误";
			_resources.content['CHECKPRINTER']="请检测您的打印机";
			_resources.content['RESTOREBG']="恢复默认背景";
			_resources.content['UPLOADBG']="上传背景图片";
			_resources.content['FULLSCREEN']="全屏";
			_resources.content['PROMPT']="提示";
			_resources.content['PHOTOSIZE']="图片大小请不要超过5M！";
			_resources.content['PHOTOFORMATERROR']="图片格式不正确";
			_resources.content['PHOTOFORMAT']="可从本地上传您的电站图片，\n仅支持JPG、GIF、PNG格式，且文件小于5M。";
			_resources.content['PREVIEW']="预览图标";
			_resources.content['PIXELS']="80*80像素";
			_resources.content['PHOTOSELECT']="选择图片";
			_resources.content['OK']="确　定";
			_resources.content['CANCEL']="取　消";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"];
			resourceManager.addResourceBundle(_resources);
			
			_resources=new ResourceBundle("da_DK","ChartResources");
			_resources.content['DAY']="Dag";
			_resources.content['MONTH']="Måned";
			_resources.content['YEAR']="År";
			_resources.content['TOTAL']="Total";
			_resources.content['7DAYS']="7 dage";
			_resources.content['7DAYSIN']="7 dage";
			_resources.content['12MONTHS']="12 måneder";
			_resources.content['PLANTADMIN']="Anlæg admin:";
			_resources.content['PRINTER']="Printer:";
			_resources.content['PRINTTIME']="Print tid:";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Total Indtægt:";
			_resources.content['CO2']="CO2 sparet:";
			_resources.content['INVERTER']="Inverter:";
			_resources.content['MONITOR']="Skærm:";
			_resources.content['EVENT']="Begivenhed:";
			_resources.content['LASTIMPORT']="Opdatering:";
			_resources.content['REPORT']="Raport";
			_resources.content['PRINTDATAERROR']="Print data fejl";
			_resources.content['PRINTERROR']="Print fejl";
			_resources.content['CHECKPRINTER']="Venligst tjek din printer";
			_resources.content['RESTOREBG']="Genskab fabriks baggrund";
			_resources.content['UPLOADBG']="Upload baggrunds billede";
			_resources.content['FULLSCREEN']="Fuld skærm";
			_resources.content['PROMPT']="Nu";
			_resources.content['PHOTOSIZE']="Billedet må ikke være mere end 5MB";
			_resources.content['PHOTOFORMATERROR']="Billede format er ikke korrekt";
			_resources.content['PHOTOFORMAT']="Upload billed af dit eget anlæg. Billedet skal være .jpg, .gif, .png format. Billede skal være mindre end 5MB";
			_resources.content['PREVIEW']="Se billede";
			_resources.content['PIXELS']="80*80 pixels";
			_resources.content['PHOTOSELECT']="Vælg billede";
			_resources.content['OK']="OK";
			_resources.content['CANCEL']="Fortryd";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["Januar", "Februar", "Marts", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
			resourceManager.addResourceBundle(_resources);
			
			var _resources:ResourceBundle=new ResourceBundle("it_IT","ChartResources");
			_resources.content['DAY']="Giorno";
			_resources.content['MONTH']="Mese";
			_resources.content['YEAR']="Anno";
			_resources.content['TOTAL']="Totale";
			_resources.content['7DAYS']="7 giorni";
			_resources.content['7DAYSIN']="Entro 7 giorni";
			_resources.content['12MONTHS']="Nel dicembre";
			_resources.content['PLANTADMIN']="Amministratore degli impianti:";
			_resources.content['PRINTER']="Stampatore:";
			_resources.content['PRINTTIME']="Data di stampa:";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Reddito totale:";
			_resources.content['CO2']="Emissione CO2:";
			_resources.content['INVERTER']="Inverter:";
			_resources.content['MONITOR']="Monitore:";
			_resources.content['EVENT']="Eventi:";
			_resources.content['LASTIMPORT']="Aggiornamento ultimo:";
			_resources.content['REPORT']="Rapporto";
			_resources.content['PRINTDATAERROR']="Errati i dati di stampa";
			_resources.content['PRINTERROR']="Errata la stampa";
			_resources.content['CHECKPRINTER']="Si prega di controllare la Sua stampatrice";
			_resources.content['RESTOREBG']="Restaurare lo sfondo di default";
			_resources.content['UPLOADBG']="Caricare le immagini dello sfondo";
			_resources.content['FULLSCREEN']="Fullscreen";
			_resources.content['PROMPT']="Suggerimento";
			_resources.content['PHOTOSIZE']="La dimensione delle immagine non possono essere superato a 5M";
			_resources.content['PHOTOFORMATERROR']="Non è corretto il formato delle immagine";
			_resources.content['PHOTOFORMAT']="Può caricare le Sue immagini degli impianti centrali di formato solo JPG,GIF,PNG, e con le dimensioni inferiori a 5M";
			_resources.content['PREVIEW']="Anteprima d'icona";
			_resources.content['PIXELS']="Pixel 80 *80";
			_resources.content['PHOTOSELECT']="Selezionare le immagine";
			_resources.content['OK']="OK";
			_resources.content['CANCEL']="Cancella";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"];
			resourceManager.addResourceBundle(_resources);
			
			var _resources:ResourceBundle=new ResourceBundle("fr_FR","ChartResources");
			_resources.content['DAY']="Jour";
			_resources.content['MONTH']="Mois";
			_resources.content['YEAR']="Année";
			_resources.content['TOTAL']="Total";
			_resources.content['7DAYS']="7 Jours";
			_resources.content['7DAYSIN']="Dans 7 jours";
			_resources.content['12MONTHS']="Dans 12  mois";
			_resources.content['PLANTADMIN']="Administrateur de centrale électrique:";
			_resources.content['PRINTER']="Imprimeur:";
			_resources.content['PRINTTIME']="Temps d’imprimerie :";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Revenu total:";
			_resources.content['CO2']="Les réductions démissions de CO2:";
			_resources.content['INVERTER']="Onduleur:";
			_resources.content['MONITOR']="Moniteur:";
			_resources.content['EVENT']="Evénement:";
			_resources.content['LASTIMPORT']="Temps des données mises à jour:";
			_resources.content['REPORT']="Rapport";
			_resources.content['PRINTDATAERROR']="Erreur des données imprimées";
			_resources.content['PRINTERROR']="Erreur d’imprimerie";
			_resources.content['CHECKPRINTER']="Testez votre imprimante";
			_resources.content['RESTOREBG']="Revenez à arrière-plan approuvé";
			_resources.content['UPLOADBG']="Téléchargez photo d’arrière-plan";
			_resources.content['FULLSCREEN']="Plein écran";
			_resources.content['PROMPT']="Rappel";
			_resources.content['PHOTOSIZE']="Format de photo ne ​​dépasse pas 5M!";
			_resources.content['PHOTOFORMATERROR']="Format de photo n’est pas correct!";
			_resources.content['PHOTOFORMAT']="Permettez de télécharger votre photo de centrale électrique du local,\n prenez uniquement en format de JPG,GIF,PNG,format maximum de 5M.";
			_resources.content['PREVIEW']="Aperçu de l'icône";
			_resources.content['PIXELS']="80*80 pixels";
			_resources.content['PHOTOSELECT']="Sélectionnez la photo";
			_resources.content['OK']="Confirmer";
			_resources.content['CANCEL']="Annuler";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"];
			resourceManager.addResourceBundle(_resources);
			
			var _resources:ResourceBundle=new ResourceBundle("de_DE","ChartResources");
			_resources.content['DAY']="Tag";
			_resources.content['MONTH']="Monat";
			_resources.content['YEAR']="Jahr";
			_resources.content['TOTAL']="Total";
			_resources.content['7DAYS']="7 Tage";
			_resources.content['7DAYSIN']="in 7 Tage";
			_resources.content['12MONTHS']="12 Monate";
			_resources.content['PLANTADMIN']="Kraftwerk Administrator:";
			_resources.content['PRINTER']="Drucker:";
			_resources.content['PRINTTIME']="Druck-Zeit:";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Gesammtgewinn:";
			_resources.content['CO2']="CO2 vermeiden:";
			_resources.content['INVERTER']="Umrichter:";
			_resources.content['MONITOR']="Monitor:";
			_resources.content['EVENT']="Fall:";
			_resources.content['LASTIMPORT']="zuletzt aktualisieren:";
			_resources.content['REPORT']="Bericht";
			_resources.content['PRINTDATAERROR']="Fehler beim Drucken der Daten";
			_resources.content['PRINTERROR']="Druckfehler";
			_resources.content['CHECKPRINTER']="Bitte prüfen ihren Drucker";
			_resources.content['RESTOREBG']="Wiederherstellen den Standard-Hintergrund";
			_resources.content['UPLOADBG']="Hochladen des Hintergrundbilds";
			_resources.content['FULLSCREEN']="Vollbild";
			_resources.content['PROMPT']="Eingabeaufforderung";
			_resources.content['PHOTOSIZE']="Größe der Fotos bitte nicht über 5 M!";
			_resources.content['PHOTOFORMATERROR']="Bildformat ist nicht richtig";
			_resources.content['PHOTOFORMAT']="Zum Hochladen des Kraftwerk-Bildes werden nur JPG GIF PNG unterstürzt und Dateien kleiner als 5M";
			_resources.content['PREVIEW']="Vorschau Symbol";
			_resources.content['PIXELS']="80*80 Pixel";
			_resources.content['PHOTOSELECT']="Wählen Sie ein Foto";
			_resources.content['OK']="Okay";
			_resources.content['CANCEL']="Abbrechen";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"];
			resourceManager.addResourceBundle(_resources);
			
			var _resources:ResourceBundle=new ResourceBundle("es_ES","ChartResources");
			_resources.content['DAY']="Día";
			_resources.content['MONTH']="Mes";
			_resources.content['YEAR']="Año";
			_resources.content['TOTAL']="Total";
			_resources.content['7DAYS']="7 Días";
			_resources.content['7DAYSIN']="Dentro de 7 Días";
			_resources.content['12MONTHS']="12 meses";
			_resources.content['PLANTADMIN']="Planta administración:";
			_resources.content['PRINTER']="Imprimidor:";
			_resources.content['PRINTTIME']="Tiepo de imprimición:";
			_resources.content['ETODAY']="E-Today:";
			_resources.content['ETOTAL']="E-Total:";
			_resources.content['ALLINCOME']="Total yield:";
			_resources.content['CO2']="CO2 avoided:";
			_resources.content['INVERTER']="Inverter:";
			_resources.content['MONITOR']="Monitor:";
			_resources.content['EVENT']="Event:";
			_resources.content['LASTIMPORT']="Last update:";
			_resources.content['REPORT']="Informe";
			_resources.content['PRINTDATAERROR']="Imprimición Dato Error";
			_resources.content['PRINTERROR']="Error de imprimición";
			_resources.content['CHECKPRINTER']="Por favor examinar tu imprimidor";
			_resources.content['RESTOREBG']="Restaurar el fondo de falta";
			_resources.content['UPLOADBG']="Cargar la imagen de fondo";
			_resources.content['FULLSCREEN']="Pantalla completa";
			_resources.content['PROMPT']="Pronto";
			_resources.content['PHOTOSIZE']="Tamaño de la foto por favor, no más de 5 M!";
			_resources.content['PHOTOFORMATERROR']="Formato de imagen no es correcto!";
			_resources.content['PHOTOFORMAT']="De local a cargar la imagen de la estación de energía, sólo admite formatos JPG GIF PNG y archivos de menos de 5 M.";
			_resources.content['PREVIEW']="Icono de vista previa";
			_resources.content['PIXELS']="80*80 píxeles";
			_resources.content['PHOTOSELECT']="Seleccione la foto";
			_resources.content['OK']="Okay";
			_resources.content['CANCEL']="Cancelar";
			_resources.content['DAYNAMES']=["S","M","T","W","T","F","S"];
			_resources.content['MONTHNAMES']=["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];
			resourceManager.addResourceBundle(_resources);
			
			resourceManager.update();
		}
	}
}